// Build step: parse kb/*.md into an embedded JS module (kb-data.js) that the
// serverless function can import directly — no runtime file reads (Vercel-safe).
// Run after editing any KB file:   node build-kb.js
//
// Each "## CHUNK N — Title" section becomes one retrievable chunk, tagged with
// its file's topic/tags from the frontmatter.

const fs = require('fs');
const path = require('path');

const KB_DIR = path.join(__dirname, 'kb');
const OUT = path.join(__dirname, 'kb-data.js');

function parseFrontmatter(src) {
  const m = /^---\n([\s\S]*?)\n---/.exec(src);
  const meta = { topic: '', tags: [] };
  if (m) {
    const topic = /topic:\s*(.+)/.exec(m[1]);
    const tags = /tags:\s*\[(.*?)\]/.exec(m[1]);
    if (topic) meta.topic = topic[1].trim();
    if (tags) meta.tags = tags[1].split(',').map((t) => t.trim().replace(/^["']|["']$/g, '')).filter(Boolean);
  }
  return meta;
}

const files = fs.readdirSync(KB_DIR).filter((f) => /^kb_\d+.*\.md$/.test(f)).sort();
const chunks = [];

for (const file of files) {
  const src = fs.readFileSync(path.join(KB_DIR, file), 'utf8');
  const fileId = file.replace(/\.md$/, '');
  const meta = parseFrontmatter(src);

  // Split on "## CHUNK ..." headers; keep the header with its body.
  const parts = src.split(/(?=^##\s+CHUNK\s+\d+)/m);
  for (const part of parts) {
    const header = /^##\s+CHUNK\s+\d+\s*[—\-–]\s*(.+)$/m.exec(part);
    if (!header) continue; // skip frontmatter/intro segment
    const title = header[1].trim();
    const text = part.trim();
    chunks.push({ file_id: fileId, topic: meta.topic, tags: meta.tags, title, text });
  }
}

fs.writeFileSync(
  OUT,
  '// GENERATED by build-kb.js from kb/*.md — do not edit by hand. Re-run: node build-kb.js\n' +
    'module.exports = ' + JSON.stringify(chunks, null, 1) + ';\n'
);

console.log('Wrote ' + OUT + ' with ' + chunks.length + ' chunks from ' + files.length + ' files.');
