// GENERATED by build-kb.js from kb/*.md — do not edit by hand. Re-run: node build-kb.js
module.exports = [
 {
  "file_id": "kb_01_credit_card_products",
  "topic": "Credit Card Products Portfolio",
  "tags": [
   "axis-bank",
   "credit-card",
   "products",
   "card-types",
   "Magnus",
   "Atlas",
   "ACE",
   "Flipkart",
   "SELECT"
  ],
  "title": "Product Overview",
  "text": "## CHUNK 1 — Product Overview\n\n### What credit cards does Axis Bank offer?\n\nAxis Bank offers a wide portfolio of credit cards across multiple categories: lifestyle/travel premium cards, cashback cards, entry-level rewards cards, and co-branded partnership cards.\n\n**Main categories:**\n- **Premium / Travel Cards:** Magnus, Atlas, Privilege, Vistara\n- **Lifestyle Cards:** SELECT, Signature, Reserve\n- **Cashback Cards:** ACE, Flipkart Axis Bank\n- **Entry-Level Rewards:** Rewards Credit Card, My Zone\n- **Co-branded Cards:** Airtel Axis Bank, Flipkart Axis Bank, IOCL Axis Bank, Samsung Axis Bank\n\nAll Axis Bank credit cards participate in the **EDGE Rewards** loyalty program.\n\n---"
 },
 {
  "file_id": "kb_01_credit_card_products",
  "topic": "Credit Card Products Portfolio",
  "tags": [
   "axis-bank",
   "credit-card",
   "products",
   "card-types",
   "Magnus",
   "Atlas",
   "ACE",
   "Flipkart",
   "SELECT"
  ],
  "title": "Magnus Credit Card",
  "text": "## CHUNK 2 — Magnus Credit Card\n\n### What is the Axis Bank Magnus Credit Card?\n\nThe Magnus is Axis Bank's flagship **super-premium lifestyle and travel card** targeting high-income individuals.\n\n- **Annual / Joining Fee:** ₹12,500 + GST\n- **Fee Waiver:** Waived on annual spends of ₹25 lakh or more\n- **Reward Rate:** 12 EDGE Reward Points per ₹200 spent\n- **Accelerated Rewards:** 35 EDGE points per ₹200 on spends exceeding ₹1.5 lakh/month\n- **Welcome Benefits:** Yatra flight voucher, Luxe gift voucher, PostCard Hotels voucher\n- **Lounge Access:** Unlimited domestic + international airport lounge visits\n- **Best For:** Frequent flyers, high-net-worth individuals who spend ₹3L+ per month\n\n---"
 },
 {
  "file_id": "kb_01_credit_card_products",
  "topic": "Credit Card Products Portfolio",
  "tags": [
   "axis-bank",
   "credit-card",
   "products",
   "card-types",
   "Magnus",
   "Atlas",
   "ACE",
   "Flipkart",
   "SELECT"
  ],
  "title": "Atlas Credit Card",
  "text": "## CHUNK 3 — Atlas Credit Card\n\n### What is the Axis Bank Atlas Credit Card?\n\nThe Atlas is a **premium travel-focused card** that earns EDGE Miles redeemable for flights and hotel bookings.\n\n- **Annual / Joining Fee:** ₹5,000 + GST (no fee waiver, but milestone rewards cover the fee)\n- **Milestone Reward:** 2,500 EDGE Miles (worth ₹5,000) on annual spends of ₹3 lakh\n- **Reward Currency:** EDGE Miles (separate from EDGE Reward Points)\n- **Lounge Access:** Complimentary domestic and international lounge access; quantum increases with tier\n- **Tiers:** Silver → Gold → Platinum based on annual spend\n- **Best For:** Frequent travellers who want to redeem rewards for flight/hotel bookings\n\n---"
 },
 {
  "file_id": "kb_01_credit_card_products",
  "topic": "Credit Card Products Portfolio",
  "tags": [
   "axis-bank",
   "credit-card",
   "products",
   "card-types",
   "Magnus",
   "Atlas",
   "ACE",
   "Flipkart",
   "SELECT"
  ],
  "title": "ACE Credit Card",
  "text": "## CHUNK 4 — ACE Credit Card\n\n### What is the Axis Bank ACE Credit Card?\n\nThe ACE is Axis Bank's most popular **cashback credit card**, aimed at everyday spenders.\n\n- **Annual / Joining Fee:** ₹499 + GST\n- **Cashback Rate:**\n  - 5% cashback on utility bill payments via Google Pay\n  - 4% cashback on Swiggy, Zomato, Ola\n  - 2% unlimited cashback on all other spends\n- **Cashback Credit:** Directly credited to card account — no redemption hassle\n- **Lounge Access:** 4 complimentary domestic lounge visits per year\n- **Best For:** Salaried individuals who pay utility bills digitally and spend on food delivery\n\n---"
 },
 {
  "file_id": "kb_01_credit_card_products",
  "topic": "Credit Card Products Portfolio",
  "tags": [
   "axis-bank",
   "credit-card",
   "products",
   "card-types",
   "Magnus",
   "Atlas",
   "ACE",
   "Flipkart",
   "SELECT"
  ],
  "title": "Flipkart Axis Bank Credit Card",
  "text": "## CHUNK 5 — Flipkart Axis Bank Credit Card\n\n### What is the Flipkart Axis Bank Credit Card?\n\nA co-branded card with **Flipkart** offering enhanced benefits on Flipkart and partner brands.\n\n- **Annual / Joining Fee:** ₹500 + GST\n- **Cashback Rate:**\n  - 5% cashback on Flipkart and Myntra\n  - 4% cashback on preferred partners (Cleartrip, PVR, Uber, etc.)\n  - 1.5% cashback on all other spends\n- **Welcome Benefit:** ₹500 Flipkart voucher on first transaction\n- **Lounge Access:** 4 complimentary domestic lounge visits per year\n- **Best For:** Regular Flipkart/Myntra shoppers\n\n---"
 },
 {
  "file_id": "kb_01_credit_card_products",
  "topic": "Credit Card Products Portfolio",
  "tags": [
   "axis-bank",
   "credit-card",
   "products",
   "card-types",
   "Magnus",
   "Atlas",
   "ACE",
   "Flipkart",
   "SELECT"
  ],
  "title": "SELECT Credit Card",
  "text": "## CHUNK 6 — SELECT Credit Card\n\n### What is the Axis Bank SELECT Credit Card?\n\nSELECT is a **premium lifestyle card** offering all-round benefits on travel, dining, and entertainment.\n\n- **Annual / Joining Fee:** ₹3,000 + GST\n- **Minimum Income Required:** ₹9 lakh per annum\n- **Reward Rate:** EDGE Reward Points on every spend\n- **Key Benefits:** Complimentary airport lounge access, dining privileges, golf programme access, concierge services\n- **Best For:** Mid-to-high income earners wanting a well-rounded lifestyle card\n\n---"
 },
 {
  "file_id": "kb_01_credit_card_products",
  "topic": "Credit Card Products Portfolio",
  "tags": [
   "axis-bank",
   "credit-card",
   "products",
   "card-types",
   "Magnus",
   "Atlas",
   "ACE",
   "Flipkart",
   "SELECT"
  ],
  "title": "Rewards Credit Card (Entry-Level)",
  "text": "## CHUNK 7 — Rewards Credit Card (Entry-Level)\n\n### What is the Axis Bank Rewards Credit Card?\n\nAn **entry-level rewards card** for customers beginning their credit card journey.\n\n- **Annual / Joining Fee:** ₹250 + GST\n- **Reward Rate:** 2 EDGE Reward Points per ₹125 spent\n- **Accelerated Rate:** 10X EDGE points on apparel and departmental store spends\n- **Milestone Benefit:** 1,500 EDGE Reward Points on net monthly spends of ₹30,000\n- **Lounge Access:** 2 complimentary domestic lounge visits per quarter\n- **Best For:** First-time credit card users or those looking for simple rewards\n\n---"
 },
 {
  "file_id": "kb_01_credit_card_products",
  "topic": "Credit Card Products Portfolio",
  "tags": [
   "axis-bank",
   "credit-card",
   "products",
   "card-types",
   "Magnus",
   "Atlas",
   "ACE",
   "Flipkart",
   "SELECT"
  ],
  "title": "Airtel Axis Bank Credit Card",
  "text": "## CHUNK 8 — Airtel Axis Bank Credit Card\n\n### What is the Airtel Axis Bank Credit Card?\n\nA co-branded card with **Airtel** offering cashback on Airtel services and other spends.\n\n- **Annual / Joining Fee:** ₹500 + GST\n- **Cashback Rate:**\n  - 25% cashback on Airtel recharges, broadband, DTH via Airtel Thanks app\n  - 10% cashback on Swiggy, BigBasket, Zomato\n  - 1% cashback on all other spends\n- **Best For:** Airtel subscribers who want to maximize savings on their Airtel bills\n\n---"
 },
 {
  "file_id": "kb_01_credit_card_products",
  "topic": "Credit Card Products Portfolio",
  "tags": [
   "axis-bank",
   "credit-card",
   "products",
   "card-types",
   "Magnus",
   "Atlas",
   "ACE",
   "Flipkart",
   "SELECT"
  ],
  "title": "How to Choose the Right Axis Bank Credit Card",
  "text": "## CHUNK 9 — How to Choose the Right Axis Bank Credit Card\n\n### Which Axis Bank credit card is right for me?\n\nUse the following guide to select the best card:\n\n| Your Primary Goal | Recommended Card |\n|---|---|\n| Maximize travel & high spends | Magnus |\n| Earn miles for flight/hotel redemptions | Atlas |\n| Simple cashback with no fuss | ACE |\n| Flipkart/Myntra shopping | Flipkart Axis Bank |\n| All-round lifestyle benefits | SELECT |\n| First credit card / entry-level | Rewards Credit Card |\n| Airtel user saving on bills | Airtel Axis Bank |\n\n> **Note:** Card offerings and fees are subject to change. Always verify current terms on the Axis Bank website or by calling 1860-419-5555."
 },
 {
  "file_id": "kb_02_eligibility_application",
  "topic": "Credit Card Eligibility and Application Process",
  "tags": [
   "axis-bank",
   "credit-card",
   "eligibility",
   "documents",
   "KYC",
   "CIBIL",
   "application",
   "income"
  ],
  "title": "Basic Eligibility Criteria",
  "text": "## CHUNK 1 — Basic Eligibility Criteria\n\n### Who is eligible to apply for an Axis Bank Credit Card?\n\nTo be eligible for an Axis Bank Credit Card, you must meet the following basic criteria:\n\n- **Age:** Between 18 and 70 years\n- **Citizenship:** Indian resident or Non-Resident Indian (NRI)\n- **Employment:** Salaried or self-employed\n- **Income:** Minimum income requirement varies by card variant\n- **Credit Score:** A CIBIL score of 750 or above is generally preferred\n- **Existing relationship:** Existing Axis Bank account holders may get priority processing\n\n> Axis Bank independently assesses credit risk per RBI guidelines — a high score does not guarantee approval.\n\n---"
 },
 {
  "file_id": "kb_02_eligibility_application",
  "topic": "Credit Card Eligibility and Application Process",
  "tags": [
   "axis-bank",
   "credit-card",
   "eligibility",
   "documents",
   "KYC",
   "CIBIL",
   "application",
   "income"
  ],
  "title": "Income Requirements by Card Type",
  "text": "## CHUNK 2 — Income Requirements by Card Type\n\n### What is the minimum income required for Axis Bank credit cards?\n\nMinimum income requirements vary by card variant:\n\n| Card | Minimum Annual Income (approx.) |\n|---|---|\n| Rewards Credit Card (entry-level) | ₹3 – 4 lakh |\n| ACE Credit Card | ₹3 – 4 lakh |\n| Flipkart Axis Bank | ₹3 – 4 lakh |\n| SELECT Credit Card | ₹9 lakh |\n| Magnus Credit Card | ₹18 lakh+ |\n| Atlas Credit Card | ₹12 lakh+ |\n\n> Income eligibility can be met via salary slips, Form 16, or Income Tax Returns. Exact thresholds are subject to Axis Bank's internal credit policy and may change.\n\n---"
 },
 {
  "file_id": "kb_02_eligibility_application",
  "topic": "Credit Card Eligibility and Application Process",
  "tags": [
   "axis-bank",
   "credit-card",
   "eligibility",
   "documents",
   "KYC",
   "CIBIL",
   "application",
   "income"
  ],
  "title": "Documents Required",
  "text": "## CHUNK 3 — Documents Required\n\n### What documents are needed to apply for an Axis Bank Credit Card?\n\nYou need to submit the following documents:\n\n**Identity Proof (any one):**\n- Aadhaar Card\n- PAN Card\n- Passport\n- Voter ID Card\n- Driving Licence\n\n**Address Proof (any one):**\n- Aadhaar Card\n- Passport\n- Driving Licence\n- Ration Card\n- Utility bill (telephone/electricity — not older than 3 months)\n\n**Income Proof:**\n- Latest 3 months' salary slips (for salaried applicants)\n- Form 16 / Income Tax Return (for salaried or self-employed)\n- Audited P&L / Balance Sheet for business owners\n\n**Photograph:**\n- Recent passport-size colour photograph\n\n**PAN Card:** Mandatory for all credit card applications (or Form 60 if PAN is not available).\n\n---"
 },
 {
  "file_id": "kb_02_eligibility_application",
  "topic": "Credit Card Eligibility and Application Process",
  "tags": [
   "axis-bank",
   "credit-card",
   "eligibility",
   "documents",
   "KYC",
   "CIBIL",
   "application",
   "income"
  ],
  "title": "How to Apply Online",
  "text": "## CHUNK 4 — How to Apply Online\n\n### How can I apply for an Axis Bank Credit Card online?\n\n**Step-by-step online application process:**\n\n1. Visit [axisbank.com](https://www.axisbank.com) → Cards → Credit Cards\n2. Browse and select a card that matches your eligibility\n3. Click **\"Apply Now\"** on the chosen card page\n4. Enter your mobile number and verify with the OTP sent\n5. Fill in personal details: name, date of birth, PAN, address, employment type\n6. Upload required documents (identity, address, income proof)\n7. Submit the application and note the **Application Reference Number**\n8. Track your application status via the website or Axis Mobile app\n\n**Processing time:** Applications are typically reviewed within 7–10 working days. Instant approvals may be offered to pre-approved customers.\n\n---"
 },
 {
  "file_id": "kb_02_eligibility_application",
  "topic": "Credit Card Eligibility and Application Process",
  "tags": [
   "axis-bank",
   "credit-card",
   "eligibility",
   "documents",
   "KYC",
   "CIBIL",
   "application",
   "income"
  ],
  "title": "How to Apply Offline / at Branch",
  "text": "## CHUNK 5 — How to Apply Offline / at Branch\n\n### Can I apply for an Axis Bank Credit Card at a branch?\n\nYes. You can apply at any Axis Bank branch.\n\n**Offline process:**\n1. Visit your nearest Axis Bank branch with all required documents\n2. Ask the branch representative for a credit card application form\n3. Fill in the form and submit with self-attested copies of documents\n4. The bank will process the application and send updates via SMS/email\n\nAxis Bank relationship managers may also reach out proactively to eligible account holders.\n\n---"
 },
 {
  "file_id": "kb_02_eligibility_application",
  "topic": "Credit Card Eligibility and Application Process",
  "tags": [
   "axis-bank",
   "credit-card",
   "eligibility",
   "documents",
   "KYC",
   "CIBIL",
   "application",
   "income"
  ],
  "title": "Application Status Tracking",
  "text": "## CHUNK 6 — Application Status Tracking\n\n### How do I track my Axis Bank Credit Card application status?\n\nYou can track your application status through multiple channels:\n\n- **Online:** Visit axisbank.com → Credit Cards → Track Application → Enter your Application Reference Number and date of birth\n- **Axis Mobile App:** Log in → Services → Track Application\n- **Customer Care:** Call 1860-419-5555 (toll-free) or 1860-500-5555\n- **SMS:** Send your application reference number to the bank's SMS service number\n- **Branch:** Visit any Axis Bank branch with your reference number\n\n---"
 },
 {
  "file_id": "kb_02_eligibility_application",
  "topic": "Credit Card Eligibility and Application Process",
  "tags": [
   "axis-bank",
   "credit-card",
   "eligibility",
   "documents",
   "KYC",
   "CIBIL",
   "application",
   "income"
  ],
  "title": "What Happens After Approval",
  "text": "## CHUNK 7 — What Happens After Approval\n\n### What happens after my Axis Bank Credit Card is approved?\n\nAfter approval:\n\n1. You will receive an SMS and email confirmation of approval\n2. The physical card is dispatched within **7–10 working days** to your registered address via courier\n3. A separate PIN mailer may be sent or you can set your PIN digitally via Axis Mobile App\n4. Upon card receipt, you must **activate the card** before use:\n   - Via Axis Mobile App or Internet Banking\n   - By calling the automated activation number on the carrier envelope\n5. Your credit limit will be communicated via your welcome kit and SMS\n\n---"
 },
 {
  "file_id": "kb_02_eligibility_application",
  "topic": "Credit Card Eligibility and Application Process",
  "tags": [
   "axis-bank",
   "credit-card",
   "eligibility",
   "documents",
   "KYC",
   "CIBIL",
   "application",
   "income"
  ],
  "title": "Why Applications Get Rejected",
  "text": "## CHUNK 8 — Why Applications Get Rejected\n\n### Why might my Axis Bank Credit Card application be rejected?\n\nCommon reasons for rejection include:\n\n- **Low CIBIL score** (below 700): Indicates past payment defaults or high credit utilization\n- **Insufficient income:** Salary below the card's minimum threshold\n- **High existing debt:** Multiple active loans or credit cards with high outstanding\n- **Employment instability:** Frequent job changes or self-employment without 2+ years of ITR\n- **Incomplete documents:** Missing PAN, income proof, or identity/address proof\n- **Previous defaults:** History of missed EMIs or credit card payments with any lender\n- **Address in a negative location:** Axis Bank maintains an internal negative area list\n\n> **Tip:** You can check your CIBIL score for free at cibil.com. Maintaining a score above 750 significantly improves approval chances.\n\n---"
 },
 {
  "file_id": "kb_02_eligibility_application",
  "topic": "Credit Card Eligibility and Application Process",
  "tags": [
   "axis-bank",
   "credit-card",
   "eligibility",
   "documents",
   "KYC",
   "CIBIL",
   "application",
   "income"
  ],
  "title": "Add-On / Supplementary Cards",
  "text": "## CHUNK 9 — Add-On / Supplementary Cards\n\n### Can I get an add-on credit card for a family member?\n\nYes. Axis Bank offers **add-on (supplementary) cards** for family members.\n\n- **Who qualifies:** Spouse, parents, siblings, or children above 18 years\n- **How to apply:** Request via Axis Mobile App, Internet Banking, or by calling customer care\n- **Limit:** The add-on card shares the primary cardholder's credit limit\n- **Liability:** All spends on add-on cards are billed to the primary cardholder\n- **Benefits:** Add-on cards participate in the same rewards programme as the primary card"
 },
 {
  "file_id": "kb_03_fees_charges",
  "topic": "Credit Card Fees and Charges",
  "tags": [
   "axis-bank",
   "credit-card",
   "fees",
   "annual-fee",
   "interest-rate",
   "late-payment",
   "forex",
   "cash-advance",
   "charges"
  ],
  "title": "Annual Fee and Joining Fee",
  "text": "## CHUNK 1 — Annual Fee and Joining Fee\n\n### What are the annual and joining fees for Axis Bank Credit Cards?\n\nThe joining fee is the first-year annual fee. Subsequent years incur the regular annual fee.\n\n| Card | Joining / Annual Fee |\n|---|---|\n| Rewards Credit Card | ₹250 + GST |\n| ACE Credit Card | ₹499 + GST |\n| Flipkart Axis Bank | ₹500 + GST |\n| Airtel Axis Bank | ₹500 + GST |\n| SELECT Credit Card | ₹3,000 + GST |\n| Atlas Credit Card | ₹5,000 + GST |\n| Magnus Credit Card | ₹12,500 + GST |\n| Burgundy Private / PRIMUS | By invitation — fee structure varies |\n\n> GST at 18% is applicable on all fees. Annual fee waivers may apply based on annual spends.\n\n---"
 },
 {
  "file_id": "kb_03_fees_charges",
  "topic": "Credit Card Fees and Charges",
  "tags": [
   "axis-bank",
   "credit-card",
   "fees",
   "annual-fee",
   "interest-rate",
   "late-payment",
   "forex",
   "cash-advance",
   "charges"
  ],
  "title": "Annual Fee Waiver",
  "text": "## CHUNK 2 — Annual Fee Waiver\n\n### How can I get the annual fee waived on my Axis Bank Credit Card?\n\nMany Axis Bank cards offer fee waivers based on annual spends:\n\n- **Magnus:** Annual fee waived on spends ≥ ₹25 lakh per year\n- **Atlas:** No fee waiver, but the milestone reward of 2,500 EDGE Miles (worth ₹5,000) effectively offsets the fee for eligible spenders\n- **ACE / Flipkart / Rewards:** Fee waiver thresholds may apply — check your specific card's T&C\n- **SELECT:** Fee waiver based on spend milestones defined in the welcome kit\n\n**How to claim waiver:** The waiver is applied automatically at the time of annual fee billing if the spend criterion is met in the preceding year.\n\n---"
 },
 {
  "file_id": "kb_03_fees_charges",
  "topic": "Credit Card Fees and Charges",
  "tags": [
   "axis-bank",
   "credit-card",
   "fees",
   "annual-fee",
   "interest-rate",
   "late-payment",
   "forex",
   "cash-advance",
   "charges"
  ],
  "title": "Interest Rate (Finance Charges)",
  "text": "## CHUNK 3 — Interest Rate (Finance Charges)\n\n### What interest rate does Axis Bank charge on credit cards?\n\nAxis Bank charges a monthly interest rate (finance charge) ranging from **1.5% to 3.6% per month**, depending on the card variant.\n\nThis translates to an **Annualised Percentage Rate (APR) of 18% to 43.2% per year**.\n\n**When interest is charged:**\n1. When you do not pay the **full outstanding amount** by the payment due date\n2. When you make a **cash withdrawal** from an ATM using your credit card (interest accrues from the date of transaction — no grace period)\n3. When you have outstanding dues from previous months (interest is calculated on the full statement balance, not just the unpaid portion)\n4. If you opt for a **balance transfer** — applicable rate may differ\n\n> As per RBI guidelines, Axis Bank must publish APR clearly for each transaction type on its website and in the Key Fact Statement.\n\n---"
 },
 {
  "file_id": "kb_03_fees_charges",
  "topic": "Credit Card Fees and Charges",
  "tags": [
   "axis-bank",
   "credit-card",
   "fees",
   "annual-fee",
   "interest-rate",
   "late-payment",
   "forex",
   "cash-advance",
   "charges"
  ],
  "title": "Interest-Free Grace Period",
  "text": "## CHUNK 4 — Interest-Free Grace Period\n\n### Is there an interest-free period on Axis Bank credit cards?\n\nYes. Axis Bank credit cards offer an **interest-free period of up to 50 days** on retail purchases, provided:\n\n- You **pay the full outstanding balance** (not just the minimum due) by the payment due date, AND\n- You have **no cash advance outstanding** on the card\n\nIf you have any outstanding balance or cash advance, the grace period does NOT apply to new transactions — interest accrues from the date of each new purchase.\n\n---"
 },
 {
  "file_id": "kb_03_fees_charges",
  "topic": "Credit Card Fees and Charges",
  "tags": [
   "axis-bank",
   "credit-card",
   "fees",
   "annual-fee",
   "interest-rate",
   "late-payment",
   "forex",
   "cash-advance",
   "charges"
  ],
  "title": "Late Payment Fee",
  "text": "## CHUNK 5 — Late Payment Fee\n\n### What is the late payment fee for Axis Bank credit cards?\n\nLate payment fees are charged when the **minimum amount due (MAD)** is not paid by the due date.\n\n| Outstanding Balance | Late Payment Fee |\n|---|---|\n| Less than ₹500 | Nil |\n| ₹500 – ₹5,000 | ₹500 |\n| ₹5,001 – ₹10,000 | ₹750 |\n| ₹10,001 – ₹25,000 | ₹900 |\n| ₹25,001 – ₹50,000 | ₹1,100 |\n| Above ₹50,000 | ₹1,300 |\n\n**Exceptions:**\n- Late payment fee is **waived** for Burgundy Private and PRIMUS cards\n- Olympus card: ₹100 if balance is above ₹2,000\n\n> GST is applicable on late payment fees. Repeated late payments also impact your CIBIL score negatively.\n\n---"
 },
 {
  "file_id": "kb_03_fees_charges",
  "topic": "Credit Card Fees and Charges",
  "tags": [
   "axis-bank",
   "credit-card",
   "fees",
   "annual-fee",
   "interest-rate",
   "late-payment",
   "forex",
   "cash-advance",
   "charges"
  ],
  "title": "Cash Advance Fee",
  "text": "## CHUNK 6 — Cash Advance Fee\n\n### What fees apply when I withdraw cash using my Axis Bank Credit Card?\n\nCash advances (ATM withdrawals using a credit card) attract:\n\n- **Cash Advance Fee:** 2.5% of the amount withdrawn, subject to a minimum of ₹500\n- **Interest:** Finance charges apply **from the date of transaction** — there is no grace period for cash advances\n- **ATM usage:** Available at any Visa/Mastercard ATM in India and abroad\n\n> Cash advances are expensive due to immediate interest accrual. It is advisable to use this facility only in emergencies.\n\n---"
 },
 {
  "file_id": "kb_03_fees_charges",
  "topic": "Credit Card Fees and Charges",
  "tags": [
   "axis-bank",
   "credit-card",
   "fees",
   "annual-fee",
   "interest-rate",
   "late-payment",
   "forex",
   "cash-advance",
   "charges"
  ],
  "title": "Foreign Currency Transaction Fee",
  "text": "## CHUNK 7 — Foreign Currency Transaction Fee\n\n### What charges apply for international/foreign currency transactions?\n\nWhen you use your Axis Bank credit card for transactions in a foreign currency:\n\n- **Forex Markup Fee:** 3.5% of the transaction amount for most cards\n- **Exceptions:**\n  - Burgundy Private card: Nil forex markup\n  - PRIMUS card: Nil forex markup\n  - Magnus: Reduced forex markup — check card T&C\n\n> Foreign currency transactions are converted to INR using the prevailing exchange rate on the transaction date. The forex markup is charged on the converted INR amount.\n\n---"
 },
 {
  "file_id": "kb_03_fees_charges",
  "topic": "Credit Card Fees and Charges",
  "tags": [
   "axis-bank",
   "credit-card",
   "fees",
   "annual-fee",
   "interest-rate",
   "late-payment",
   "forex",
   "cash-advance",
   "charges"
  ],
  "title": "Other Fees and Charges",
  "text": "## CHUNK 8 — Other Fees and Charges\n\n### What other fees should I be aware of on my Axis Bank Credit Card?\n\n| Fee Type | Amount |\n|---|---|\n| Over-limit fee | 2.5% of the over-limit amount, min ₹550 |\n| Cheque return / auto-debit failure fee | ₹500 per instance |\n| Card replacement fee | ₹200 – ₹500 (varies by card) |\n| Duplicate statement fee | ₹100 per statement (beyond free period) |\n| Reward redemption fee (EDGE portal) | ₹99 per redemption transaction |\n| Miles / partner loyalty conversion fee | ₹199 per conversion |\n| Rent transaction fee | 1% of the rent transaction amount |\n| Fuel surcharge waiver | 1% surcharge waived at fuel stations for transactions between ₹400–₹4,000 (subject to monthly cap) |\n\n> **Reward Redemption Fee (2025 change):** Effective 2025, a fee of ₹99 is charged for each EDGE Reward redemption and ₹199 for partner miles conversion. This is an important change from the earlier free redemption model.\n\n---"
 },
 {
  "file_id": "kb_03_fees_charges",
  "topic": "Credit Card Fees and Charges",
  "tags": [
   "axis-bank",
   "credit-card",
   "fees",
   "annual-fee",
   "interest-rate",
   "late-payment",
   "forex",
   "cash-advance",
   "charges"
  ],
  "title": "Minimum Amount Due",
  "text": "## CHUNK 9 — Minimum Amount Due\n\n### How is the Minimum Amount Due (MAD) calculated?\n\nThe **Minimum Amount Due (MAD)** is the smallest payment you must make by the due date to keep your account in good standing.\n\n**Typical MAD calculation:**\n- 5% of the total outstanding balance, OR\n- Total of all EMI installments + interest + fees + any amount overdue from previous cycles\n- Whichever is higher\n\n> **Important:** Paying only the MAD does NOT avoid interest charges. Interest will be levied on the remaining outstanding amount. To avoid all interest, always pay the **full outstanding balance** by the due date."
 },
 {
  "file_id": "kb_04_rewards_benefits",
  "topic": "Rewards Programme, Cashback, and Card Benefits",
  "tags": [
   "axis-bank",
   "credit-card",
   "EDGE-rewards",
   "cashback",
   "lounge-access",
   "miles",
   "redemption",
   "milestone-benefits"
  ],
  "title": "What is the EDGE Rewards Programme?",
  "text": "## CHUNK 1 — What is the EDGE Rewards Programme?\n\n### What is Axis Bank EDGE Rewards?\n\n**Axis EDGE Rewards** is Axis Bank's unified loyalty programme that covers credit cards, debit cards, savings accounts, and other banking relationships.\n\n- **Reward Currency:** EDGE Reward Points (for most cards) or EDGE Miles (for Atlas and travel-focused cards)\n- **Earning:** Points are awarded per eligible transaction based on the card variant\n- **Redemption:** Points can be redeemed via the EDGE Rewards portal (edgerewards.axisbank.com), Axis Mobile App, or customer care\n- **Point Value:** 1 EDGE Reward Point = ₹0.20 (20 paise) for most redemption options\n- **Point Validity:** 3 years from the date of earning\n- **Minimum Balance to Redeem:** 300 EDGE Reward Points\n\n---"
 },
 {
  "file_id": "kb_04_rewards_benefits",
  "topic": "Rewards Programme, Cashback, and Card Benefits",
  "tags": [
   "axis-bank",
   "credit-card",
   "EDGE-rewards",
   "cashback",
   "lounge-access",
   "miles",
   "redemption",
   "milestone-benefits"
  ],
  "title": "How to Earn EDGE Reward Points",
  "text": "## CHUNK 2 — How to Earn EDGE Reward Points\n\n### How do I earn EDGE Reward Points on my Axis Bank credit card?\n\nReward points are earned on eligible transactions:\n\n| Card | Base Earn Rate | Accelerated Earn Rate |\n|---|---|---|\n| Rewards Credit Card | 2 pts per ₹125 | 10X on apparel & dept. stores |\n| ACE | Cashback (not points) | 5% on utility via GPay |\n| Magnus | 12 pts per ₹200 | 35 pts/₹200 above ₹1.5L/month |\n| Atlas | EDGE Miles (see CHUNK 6) | Tier-based bonus miles |\n| SELECT | Points per ₹200 | Higher rate on select categories |\n\n**Transactions that typically do NOT earn rewards:**\n- Cash advances (ATM withdrawals)\n- Fuel transactions (at most petrol pumps)\n- Rent payments\n- Wallet reloads\n- Cash-equivalent transactions\n\n---"
 },
 {
  "file_id": "kb_04_rewards_benefits",
  "topic": "Rewards Programme, Cashback, and Card Benefits",
  "tags": [
   "axis-bank",
   "credit-card",
   "EDGE-rewards",
   "cashback",
   "lounge-access",
   "miles",
   "redemption",
   "milestone-benefits"
  ],
  "title": "Milestone Benefits",
  "text": "## CHUNK 3 — Milestone Benefits\n\n### What are milestone benefits on Axis Bank credit cards?\n\nMilestone benefits are **bonus rewards credited when spending crosses a defined threshold** in a billing cycle or year.\n\n**Rewards Credit Card:**\n- 1,500 EDGE Reward Points on net spends of ₹30,000 per statement cycle\n- Excluded transactions: rent, wallet reloads, fuel, cash withdrawals\n\n**Magnus:**\n- Accelerated rate of 35 EDGE points per ₹200 kicks in when monthly spend exceeds ₹1.5 lakh\n\n**Atlas:**\n- 2,500 EDGE Miles on annual spends of ₹3 lakh (offsets the ₹5,000 annual fee)\n- Higher tier unlocks (Gold, Platinum) with higher milestone thresholds provide more lounge access\n\n**SELECT:**\n- Annual milestone benefits including bonus points or vouchers — refer to your welcome kit for the specific threshold\n\n---"
 },
 {
  "file_id": "kb_04_rewards_benefits",
  "topic": "Rewards Programme, Cashback, and Card Benefits",
  "tags": [
   "axis-bank",
   "credit-card",
   "EDGE-rewards",
   "cashback",
   "lounge-access",
   "miles",
   "redemption",
   "milestone-benefits"
  ],
  "title": "EDGE Miles (Travel Rewards)",
  "text": "## CHUNK 4 — EDGE Miles (Travel Rewards)\n\n### What are EDGE Miles and how are they different from EDGE Reward Points?\n\n**EDGE Miles** are a specialized reward currency primarily associated with the **Atlas Credit Card** and used for travel-specific redemptions.\n\n- **Earning:** Earned as EDGE Miles instead of EDGE Reward Points on Atlas card spends\n- **Value:** Typically 1 EDGE Mile ≈ ₹1–2 depending on redemption partner\n- **Redemption:** Can be redeemed for flight tickets, hotel bookings, or transferred to partner airline frequent flyer programmes\n\n**Partner Airline Miles Conversion (Atlas card):**\n- Air India Flying Returns\n- InterMiles (Jet Airways partner programme)\n- Singapore Airlines KrisFlyer\n- Vistara Club Vistara (now merged with Air India)\n\n> **Conversion fee (2025):** ₹199 per partner miles conversion transaction\n\n---"
 },
 {
  "file_id": "kb_04_rewards_benefits",
  "topic": "Rewards Programme, Cashback, and Card Benefits",
  "tags": [
   "axis-bank",
   "credit-card",
   "EDGE-rewards",
   "cashback",
   "lounge-access",
   "miles",
   "redemption",
   "milestone-benefits"
  ],
  "title": "How to Redeem EDGE Reward Points",
  "text": "## CHUNK 5 — How to Redeem EDGE Reward Points\n\n### How can I redeem my Axis Bank EDGE Reward Points?\n\n**Redemption channels:**\n1. **EDGE Rewards Portal:** Visit edgerewards.axisbank.com → Log in → Browse catalogue → Redeem\n2. **Axis Mobile App:** Go to Cards → Manage Rewards → Redeem Points\n3. **Customer Care:** Call 1860-419-5555 and request redemption\n\n**Redemption options:**\n- **Product Catalogue:** Electronics, appliances, lifestyle products\n- **E-Vouchers:** Amazon, Flipkart, Swiggy, Uber, etc.\n- **Cashback:** Credited directly to your card outstanding\n- **Airmiles:** Transfer to partner airline/hotel loyalty programmes\n- **Hotel/Flight Bookings:** Book directly via EDGE portal using points\n- **Partner Outlets:** At select merchant locations\n\n**Redemption Fee (2025 update):**\n- ₹99 per redemption transaction on the EDGE portal\n- ₹199 for conversion to partner loyalty programmes\n\n**Minimum points required:** 300 EDGE Reward Points\n\n---"
 },
 {
  "file_id": "kb_04_rewards_benefits",
  "topic": "Rewards Programme, Cashback, and Card Benefits",
  "tags": [
   "axis-bank",
   "credit-card",
   "EDGE-rewards",
   "cashback",
   "lounge-access",
   "miles",
   "redemption",
   "milestone-benefits"
  ],
  "title": "Cashback vs Reward Points",
  "text": "## CHUNK 6 — Cashback vs Reward Points\n\n### What is the difference between cashback and reward points on Axis Bank cards?\n\n| Feature | Cashback (ACE, Flipkart) | Reward Points (Rewards, Magnus, SELECT) |\n|---|---|---|\n| Form | Direct credit to card outstanding | Points credited to EDGE account |\n| Redemption | Automatic (no action needed) | Must redeem via EDGE portal or app |\n| Value | Exact ₹ value (5% = 5 paise per rupee) | Variable (1 point = ₹0.20 typically) |\n| Redemption Fee | None | ₹99 per redemption (2025) |\n| Flexibility | Lower — fixed to cash savings | Higher — products, travel, vouchers |\n| Best for | Users who want simplicity | Users who want travel/product variety |\n\n---"
 },
 {
  "file_id": "kb_04_rewards_benefits",
  "topic": "Rewards Programme, Cashback, and Card Benefits",
  "tags": [
   "axis-bank",
   "credit-card",
   "EDGE-rewards",
   "cashback",
   "lounge-access",
   "miles",
   "redemption",
   "milestone-benefits"
  ],
  "title": "Airport Lounge Access",
  "text": "## CHUNK 7 — Airport Lounge Access\n\n### Does my Axis Bank Credit Card include airport lounge access?\n\nMost mid-range and premium Axis Bank cards include complimentary airport lounge access:\n\n| Card | Domestic Lounge Access | International Lounge Access |\n|---|---|---|\n| Rewards Credit Card | 2/quarter | Nil |\n| ACE Credit Card | 4/year | Nil |\n| Flipkart Axis Bank | 4/year | Nil |\n| SELECT | Unlimited (select airports) | Limited |\n| Magnus | Unlimited | Unlimited |\n| Atlas (Silver) | 8/year domestic | 4/year international |\n| Atlas (Gold/Platinum) | Higher allocation | Higher allocation |\n\n**How to access:** Present your Axis Bank credit card at participating lounge reception desks. Some lounges use the DreamFolks app for access management.\n\n---"
 },
 {
  "file_id": "kb_04_rewards_benefits",
  "topic": "Rewards Programme, Cashback, and Card Benefits",
  "tags": [
   "axis-bank",
   "credit-card",
   "EDGE-rewards",
   "cashback",
   "lounge-access",
   "miles",
   "redemption",
   "milestone-benefits"
  ],
  "title": "Other Card Benefits",
  "text": "## CHUNK 8 — Other Card Benefits\n\n### What other benefits do Axis Bank credit cards offer?\n\n**Common benefits across premium cards:**\n- **Fuel Surcharge Waiver:** 1% surcharge waived at fuel stations for transactions between ₹400–₹4,000 (subject to a monthly cap of ₹500)\n- **Dining Offers:** Discounts at partner restaurants via Axis Bank dining programme\n- **Shopping Offers:** Exclusive discounts at Axis Bank partner merchants (Amazon, Myntra, Nykaa, etc.)\n- **Insurance Benefits:** Personal accident cover, lost card liability cover (varies by card)\n- **Concierge Services:** Available on Magnus, SELECT, and other premium cards\n- **Golf Programme:** Complimentary golf rounds at select courses (SELECT, Magnus, Premium cards)\n- **Annual Memberships:** Worth ₹1,000 per year on Rewards Credit Card (e.g., Swiggy One, Zomato Gold)\n\n---"
 },
 {
  "file_id": "kb_04_rewards_benefits",
  "topic": "Rewards Programme, Cashback, and Card Benefits",
  "tags": [
   "axis-bank",
   "credit-card",
   "EDGE-rewards",
   "cashback",
   "lounge-access",
   "miles",
   "redemption",
   "milestone-benefits"
  ],
  "title": "Point Expiry and Account Closure",
  "text": "## CHUNK 9 — Point Expiry and Account Closure\n\n### Do EDGE Reward Points expire? What happens if I close my card?\n\n- **Expiry:** EDGE Reward Points are valid for **3 years** from the date of earning\n- **Card Closure:** Upon closure of your credit card account, all accumulated EDGE Reward Points are **forfeited** unless redeemed before closure\n- **Account Suspension:** Points may be frozen if your card account becomes delinquent (overdue payments)\n- **Checking Balance:** View your current EDGE points balance via Axis Mobile App → Cards → View Rewards, or via the EDGE portal\n\n> **Recommendation:** Redeem points before initiating card closure to avoid loss of accumulated rewards."
 },
 {
  "file_id": "kb_05_billing_payments",
  "topic": "Billing, Statements, and Payment",
  "tags": [
   "axis-bank",
   "credit-card",
   "billing",
   "statement",
   "minimum-due",
   "payment-due-date",
   "EMI",
   "balance-transfer",
   "auto-debit"
  ],
  "title": "Billing Cycle",
  "text": "## CHUNK 1 — Billing Cycle\n\n### What is the billing cycle for Axis Bank credit cards?\n\n- **Billing Cycle:** Typically a **30-day period** during which all transactions are accumulated\n- **Statement Generation:** At the end of each billing cycle, a monthly statement is generated\n- **Statement Date (also called Closing Date):** The date on which the billing cycle ends and the statement is generated\n- **Payment Due Date:** Usually **15–18 days after the statement date**, giving you a repayment window\n\n> As per RBI guidelines, Axis Bank must provide cardholders with **at least 15 days (one fortnight)** to make payment after the statement is generated. Axis Bank typically provides more than this minimum.\n\n**Example:**\n- Statement date: 5th of each month\n- Payment due date: 20th–25th of each month\n- Transactions from 6th of previous month to 5th of current month appear on the statement\n\n---"
 },
 {
  "file_id": "kb_05_billing_payments",
  "topic": "Billing, Statements, and Payment",
  "tags": [
   "axis-bank",
   "credit-card",
   "billing",
   "statement",
   "minimum-due",
   "payment-due-date",
   "EMI",
   "balance-transfer",
   "auto-debit"
  ],
  "title": "Reading Your Credit Card Statement",
  "text": "## CHUNK 2 — Reading Your Credit Card Statement\n\n### What information is on my Axis Bank credit card statement?\n\nYour monthly credit card statement includes:\n\n1. **Statement Period:** Start and end dates of the billing cycle\n2. **Statement Date / Closing Date**\n3. **Payment Due Date**\n4. **Total Outstanding Balance:** Full amount owed including purchases, interest, and fees\n5. **Minimum Amount Due (MAD):** Minimum payment required to avoid late fee\n6. **Transaction Details:** Itemised list of all debits (purchases, fees, cash advances) and credits (payments, cashback)\n7. **Reward Points Summary:** Points earned, redeemed, and balance\n8. **Credit Limit & Available Credit**\n9. **Interest & Charges Breakdown:** Finance charges, late fees, other charges\n\nStatements are sent via email to your registered email address. You can also view them on the Axis Mobile App or Internet Banking.\n\n---"
 },
 {
  "file_id": "kb_05_billing_payments",
  "topic": "Billing, Statements, and Payment",
  "tags": [
   "axis-bank",
   "credit-card",
   "billing",
   "statement",
   "minimum-due",
   "payment-due-date",
   "EMI",
   "balance-transfer",
   "auto-debit"
  ],
  "title": "How to Pay Your Credit Card Bill",
  "text": "## CHUNK 3 — How to Pay Your Credit Card Bill\n\n### How can I pay my Axis Bank Credit Card bill?\n\n**Online payment methods:**\n1. **Axis Mobile App:** Cards → Credit Card → Pay Now → Select amount (full/MAD/custom)\n2. **Axis Internet Banking:** Payments → Credit Card Payment\n3. **NEFT/RTGS:** Use your 16-digit Axis Bank Credit Card number as the account number and Axis Bank IFSC code\n4. **IMPS:** Available through any bank's mobile app for instant transfers\n5. **UPI:** Pay via Google Pay, PhonePe, Paytm etc. using your credit card payment VPA\n6. **BillDesk / Online Portals:** Pay from any bank via the payment gateway on axisbank.com\n\n**Offline payment methods:**\n1. **Axis Bank Branch:** Cash or cheque at any branch\n2. **Axis Bank ATM:** Insert card → Select \"Bill Payment\" option\n3. **Auto-Debit:** Set up standing instructions to auto-debit from your Axis Bank savings account\n\n> NEFT and cheque payments may take 1–2 days to reflect. Pay at least **3 days before the due date** to avoid late fees.\n\n---"
 },
 {
  "file_id": "kb_05_billing_payments",
  "topic": "Billing, Statements, and Payment",
  "tags": [
   "axis-bank",
   "credit-card",
   "billing",
   "statement",
   "minimum-due",
   "payment-due-date",
   "EMI",
   "balance-transfer",
   "auto-debit"
  ],
  "title": "Auto-Debit Facility",
  "text": "## CHUNK 4 — Auto-Debit Facility\n\n### How do I set up auto-debit for my Axis Bank Credit Card?\n\nAuto-debit automatically deducts your credit card bill from a linked Axis Bank savings/current account on the due date.\n\n**How to set up:**\n1. Log in to Axis Mobile App or Internet Banking\n2. Go to Credit Card → Settings → Auto Pay\n3. Choose auto-debit option:\n   - **Full Outstanding Balance** (recommended — avoids all interest)\n   - **Minimum Amount Due**\n   - **Fixed Custom Amount**\n4. Link your Axis Bank account and confirm\n\n**Benefits:**\n- Ensures payment is never missed\n- Prevents late payment fees\n- Protects your CIBIL score\n\n> Auto-debit from a **non-Axis bank account** can be set up via NACH mandate — request the form at a branch or via customer care.\n\n---"
 },
 {
  "file_id": "kb_05_billing_payments",
  "topic": "Billing, Statements, and Payment",
  "tags": [
   "axis-bank",
   "credit-card",
   "billing",
   "statement",
   "minimum-due",
   "payment-due-date",
   "EMI",
   "balance-transfer",
   "auto-debit"
  ],
  "title": "EMI Conversion",
  "text": "## CHUNK 5 — EMI Conversion\n\n### Can I convert my credit card purchases to EMI?\n\nYes. Axis Bank offers EMI conversion for eligible transactions.\n\n**Eligibility:**\n- Transaction amount must be at least **₹2,500**\n- Transaction must be a retail purchase (not cash advance, fuel, gold, or jewellery)\n- Card must not be delinquent (overdue)\n\n**EMI Tenure Options:** 3, 6, 9, 12, 18, or 24 months\n\n**Interest Rate:** Approximately **1.5% per month** on the reducing balance (varies by offer and tenure)\n\n**How to Convert:**\n1. Axis Mobile App → Cards → EMI → Select Transaction → Choose Tenure\n2. SMS/Customer Care conversion for eligible transactions\n3. At the point of purchase (for partner merchants offering 0% EMI)\n\n**What happens to credit limit:**\n- The EMI principal amount reduces your available credit limit\n- As you pay each EMI, your credit limit is partially restored\n\n**Exclusions:** Gold, jewellery, cash withdrawals, balance transfers, and corporate cards are not eligible.\n\n---"
 },
 {
  "file_id": "kb_05_billing_payments",
  "topic": "Billing, Statements, and Payment",
  "tags": [
   "axis-bank",
   "credit-card",
   "billing",
   "statement",
   "minimum-due",
   "payment-due-date",
   "EMI",
   "balance-transfer",
   "auto-debit"
  ],
  "title": "Zero-Cost / No-Cost EMI",
  "text": "## CHUNK 6 — Zero-Cost / No-Cost EMI\n\n### What is no-cost EMI on Axis Bank credit cards?\n\n**No-cost EMI (0% EMI)** is available at select partner merchants where the interest cost is absorbed by the merchant or Axis Bank as a promotional offer.\n\n- **How it works:** You pay only the principal in monthly instalments — no interest\n- **Availability:** Online platforms (Flipkart, Amazon, Myntra), offline retail stores\n- **Processing fee:** A processing fee may apply (₹199–₹499 + GST) — check the specific offer\n- **Eligibility:** Depends on the merchant, purchase amount, and card type\n\n> During no-cost EMI periods, GST on interest may still be charged in some cases — verify before opting in.\n\n---"
 },
 {
  "file_id": "kb_05_billing_payments",
  "topic": "Billing, Statements, and Payment",
  "tags": [
   "axis-bank",
   "credit-card",
   "billing",
   "statement",
   "minimum-due",
   "payment-due-date",
   "EMI",
   "balance-transfer",
   "auto-debit"
  ],
  "title": "Balance Transfer",
  "text": "## CHUNK 7 — Balance Transfer\n\n### Can I transfer my balance from another credit card to my Axis Bank card?\n\nYes. Axis Bank offers a **Balance Transfer (BT)** facility to transfer outstanding balances from other banks' credit cards to your Axis Bank credit card at a lower interest rate.\n\n- **Purpose:** Consolidate high-interest debt from other cards at a lower promotional rate\n- **Typical BT Rate:** Lower than standard finance charges — promotional rate varies by offer\n- **Tenure:** Usually 3–12 months\n- **Minimum Transfer Amount:** ₹5,000 typically\n- **Processing Fee:** 1–2% of the transferred amount, or as per specific offer terms\n\n**How to apply:**\n- Contact Axis Bank customer care at 1860-419-5555\n- Log in to Internet Banking → Credit Card → Balance Transfer → Apply\n\n> Interest charges apply from the transfer date. Evaluate the total cost (processing fee + interest) before transferring.\n\n---"
 },
 {
  "file_id": "kb_05_billing_payments",
  "topic": "Billing, Statements, and Payment",
  "tags": [
   "axis-bank",
   "credit-card",
   "billing",
   "statement",
   "minimum-due",
   "payment-due-date",
   "EMI",
   "balance-transfer",
   "auto-debit"
  ],
  "title": "What Happens If I Miss a Payment",
  "text": "## CHUNK 8 — What Happens If I Miss a Payment\n\n### What happens if I miss my Axis Bank credit card payment due date?\n\nIf you miss the payment due date:\n\n1. **Late Payment Fee:** Charged as per the fee slab (see kb_03 for details)\n2. **Interest on Outstanding:** Finance charges apply from the statement date on the full outstanding balance\n3. **Grace Period Lost:** You lose the interest-free grace period — interest applies on all new purchases from the transaction date\n4. **CIBIL Score Impact:** Late payment is reported to credit bureaus (CIBIL, Experian, CRIF) — negatively affects your credit score\n5. **Account Suspension Risk:** Repeated non-payment can lead to card suspension or account being marked delinquent\n\n**If you can't pay in full:**\n- At minimum, pay the **Minimum Amount Due (MAD)** to avoid late fees\n- Contact Axis Bank customer care to discuss hardship payment plans if you are unable to make payments\n\n---"
 },
 {
  "file_id": "kb_05_billing_payments",
  "topic": "Billing, Statements, and Payment",
  "tags": [
   "axis-bank",
   "credit-card",
   "billing",
   "statement",
   "minimum-due",
   "payment-due-date",
   "EMI",
   "balance-transfer",
   "auto-debit"
  ],
  "title": "Disputes on Billing Statements",
  "text": "## CHUNK 9 — Disputes on Billing Statements\n\n### I see an incorrect charge on my statement — what should I do?\n\nIf you notice an incorrect or unrecognised charge on your Axis Bank credit card statement:\n\n1. **Do not wait** — disputes must be filed within **30 days of the statement date**\n2. **Raise a dispute through:**\n   - Axis Mobile App → Cards → Dispute a Transaction\n   - Email: [email protected]\n   - Customer Care: 1860-419-5555\n   - Submit the **Cardholder Dispute Form** (downloadable from axisbank.com)\n3. **Provide details:** Transaction date, merchant name, amount, and reason for dispute\n4. **Bank's TAT:** Axis Bank will investigate and resolve within **30 days** of the dispute date\n5. **Temporary credit:** A temporary credit may be applied to your account while the investigation is ongoing\n\n> As per RBI guidelines, if your query is not resolved within 30 days, you can escalate to the RBI Ombudsman."
 },
 {
  "file_id": "kb_06_disputes_fraud_security",
  "topic": "Disputes, Fraud, and Card Security",
  "tags": [
   "axis-bank",
   "credit-card",
   "fraud",
   "dispute",
   "chargeback",
   "block-card",
   "phishing",
   "unauthorized-transaction",
   "security"
  ],
  "title": "What to Do Immediately After Fraud",
  "text": "## CHUNK 1 — What to Do Immediately After Fraud\n\n### I see a fraudulent transaction on my Axis Bank Credit Card — what should I do immediately?\n\n**Immediate steps (act within minutes/hours):**\n\n1. **Block your card immediately:**\n   - Axis Mobile App → Cards → Block Card (instant)\n   - SMS: Send \"BLOCK XXXX\" (last 4 digits of card) to 5676782\n   - Call 1860-419-5555 (24x7 helpline)\n\n2. **Do NOT share your OTP, CVV, card PIN, or internet banking password** with anyone — Axis Bank will never ask for these\n\n3. **Document the transaction:** Note the date, time, merchant name, and amount of the suspicious transaction\n\n4. **File a dispute** within 30 days of the statement date (see CHUNK 3 below)\n\n5. **File a police complaint** for significant fraudulent transactions — keep the FIR copy for your records\n\n> The faster you report, the better your chances of a full reversal. As per RBI guidelines, your liability may be zero for fraud reported promptly.\n\n---"
 },
 {
  "file_id": "kb_06_disputes_fraud_security",
  "topic": "Disputes, Fraud, and Card Security",
  "tags": [
   "axis-bank",
   "credit-card",
   "fraud",
   "dispute",
   "chargeback",
   "block-card",
   "phishing",
   "unauthorized-transaction",
   "security"
  ],
  "title": "Types of Credit Card Fraud",
  "text": "## CHUNK 2 — Types of Credit Card Fraud\n\n### What are the common types of credit card fraud I should know about?\n\n**Common fraud types:**\n\n- **Unauthorized card-present transaction:** Someone physically uses your stolen or cloned card\n- **Card-not-present (CNP) fraud:** Your card details (number, CVV, expiry) are used for online transactions without the physical card\n- **Phishing:** Fraudulent emails/SMSs/calls impersonating Axis Bank to steal your credentials\n- **Vishing:** Fraudulent phone calls claiming to be bank representatives asking for OTP or card details\n- **Skimming:** Physical device attached to ATMs or POS terminals that copies your card data\n- **SIM swap fraud:** Fraudsters convince your mobile operator to issue a new SIM with your number, gaining access to OTPs\n\n**Red flags:**\n- OTP received for a transaction you didn't initiate\n- Unexpected decline of your card at a merchant\n- Statement showing transactions in a city you haven't visited\n\n---"
 },
 {
  "file_id": "kb_06_disputes_fraud_security",
  "topic": "Disputes, Fraud, and Card Security",
  "tags": [
   "axis-bank",
   "credit-card",
   "fraud",
   "dispute",
   "chargeback",
   "block-card",
   "phishing",
   "unauthorized-transaction",
   "security"
  ],
  "title": "Filing a Transaction Dispute (Chargeback)",
  "text": "## CHUNK 3 — Filing a Transaction Dispute (Chargeback)\n\n### How do I file a dispute for an incorrect or fraudulent transaction?\n\n**Eligibility:** Disputes must be filed within **30 days of the statement date**.\n\n**Common dispute reasons:**\n- Transaction not initiated by cardholder (unauthorized)\n- Goods/services ordered but not received\n- Duplicate billing (charged twice for same transaction)\n- Wrong amount charged\n- Cancelled subscription/membership still being billed\n- Merchant not processing a refund\n\n**How to file a dispute:**\n1. **Axis Mobile App:** Cards → Transaction History → Select Transaction → Dispute\n2. **Email:** Send details + Cardholder Dispute Form to [email protected]\n3. **Customer Care:** Call 1860-419-5555 and raise a dispute request\n4. **Online Portal:** Visit application.axis.bank.in → Report Fraud/Dispute\n\n**What to include in your dispute:**\n- Your name, card number (last 4 digits), registered mobile number\n- Transaction date, amount, and merchant name\n- Reason for dispute with supporting documentation (e.g., cancellation confirmation, receipt showing different amount)\n\n---"
 },
 {
  "file_id": "kb_06_disputes_fraud_security",
  "topic": "Disputes, Fraud, and Card Security",
  "tags": [
   "axis-bank",
   "credit-card",
   "fraud",
   "dispute",
   "chargeback",
   "block-card",
   "phishing",
   "unauthorized-transaction",
   "security"
  ],
  "title": "Chargeback Process and Timeline",
  "text": "## CHUNK 4 — Chargeback Process and Timeline\n\n### How does the Axis Bank chargeback investigation work?\n\n**Step-by-step process:**\n\n1. **Dispute Filed:** You raise a dispute within 30 days of statement date\n2. **Acknowledgement:** Axis Bank acknowledges your dispute (typically within 1–2 business days)\n3. **Temporary Credit:** A provisional credit may be applied to your account while investigation is ongoing (amount is blocked, not spendable)\n4. **Investigation:** Axis Bank contacts the merchant's bank (acquirer) to verify the transaction — typically takes 15–45 days\n5. **Merchant Response:** If the merchant cannot prove the transaction was legitimate, the chargeback is resolved in your favour\n6. **Final Resolution:**\n   - **Chargeback approved:** Temporary credit becomes permanent; amount fully reversed\n   - **Chargeback rejected:** Temporary credit is reversed; your account is debited\n\n**Timeline:** RBI requires resolution within **30 working days** of dispute filing.\n\n> If unresolved within 30 days, you can escalate to the **RBI Ombudsman**.\n\n---"
 },
 {
  "file_id": "kb_06_disputes_fraud_security",
  "topic": "Disputes, Fraud, and Card Security",
  "tags": [
   "axis-bank",
   "credit-card",
   "fraud",
   "dispute",
   "chargeback",
   "block-card",
   "phishing",
   "unauthorized-transaction",
   "security"
  ],
  "title": "Blocking and Replacing Your Card",
  "text": "## CHUNK 5 — Blocking and Replacing Your Card\n\n### How do I block my Axis Bank Credit Card if it is lost or stolen?\n\n**Methods to block your card:**\n\n| Channel | Method | Availability |\n|---|---|---|\n| Axis Mobile App | Cards → Block Card → Select Reason | 24x7 |\n| Axis Internet Banking | Cards → Manage Card → Block Card | 24x7 |\n| SMS | Send \"BLOCK XXXX\" (last 4 digits) to 5676782 | 24x7 |\n| Customer Care | Call 1860-419-5555 | 24x7 |\n| Axis Bank Branch | Visit any branch with ID proof | During business hours |\n\n**After blocking:**\n- Request a card replacement immediately\n- Replacement card is dispatched within 7–10 working days\n- Your credit limit and account history carry over to the new card\n- **Card replacement fee:** ₹200–₹500 depending on card type\n\n---"
 },
 {
  "file_id": "kb_06_disputes_fraud_security",
  "topic": "Disputes, Fraud, and Card Security",
  "tags": [
   "axis-bank",
   "credit-card",
   "fraud",
   "dispute",
   "chargeback",
   "block-card",
   "phishing",
   "unauthorized-transaction",
   "security"
  ],
  "title": "Zero Liability Policy (RBI Guidelines)",
  "text": "## CHUNK 6 — Zero Liability Policy (RBI Guidelines)\n\n### Am I liable for unauthorized transactions on my Axis Bank Credit Card?\n\nAs per **RBI's guidelines on unauthorized electronic transactions**, your liability depends on where the fault lies:\n\n| Scenario | Your Liability |\n|---|---|\n| Fraud due to bank's negligence/system breach | **ZERO** — full reversal |\n| Third-party fraud (no contribution from customer or bank) — reported within 3 working days | **ZERO** — full reversal |\n| Third-party fraud — reported within 4–7 working days | Limited liability (capped amount per card type) |\n| Third-party fraud — reported after 7 working days | Liability as per bank's approved policy |\n| Customer's own negligence (shared PIN/OTP) | **Customer is liable** |\n\n> Key principle: **Report fraud as quickly as possible.** The sooner you report, the better your protection. Sharing OTP or PIN with anyone — including someone claiming to be from Axis Bank — makes you liable.\n\n---"
 },
 {
  "file_id": "kb_06_disputes_fraud_security",
  "topic": "Disputes, Fraud, and Card Security",
  "tags": [
   "axis-bank",
   "credit-card",
   "fraud",
   "dispute",
   "chargeback",
   "block-card",
   "phishing",
   "unauthorized-transaction",
   "security"
  ],
  "title": "Card Security Best Practices",
  "text": "## CHUNK 7 — Card Security Best Practices\n\n### How can I keep my Axis Bank Credit Card secure?\n\n**Recommended security practices:**\n\n**Online Security:**\n- Never share your Card Number, CVV, Expiry Date, OTP, or PIN with anyone — Axis Bank will never ask for these\n- Always check that the website URL starts with \"https://\" before entering card details\n- Avoid using public Wi-Fi for online transactions\n- Enable transaction alerts (SMS + email) for every transaction\n\n**Physical Card Security:**\n- Keep your card in a safe place; do not leave it unattended\n- Shield the keypad when entering your PIN at ATMs or POS terminals\n- Check ATM machines for suspicious attachments (skimming devices) before inserting your card\n- Memorize your PIN — do not write it on the card or keep it with the card\n\n**Digital Controls (via Axis Mobile App):**\n- Enable/disable **international transactions** (turn on only when travelling)\n- Enable/disable **online transactions**\n- Enable/disable **contactless payments**\n- Set **transaction limits** for specific channels\n\n---"
 },
 {
  "file_id": "kb_06_disputes_fraud_security",
  "topic": "Disputes, Fraud, and Card Security",
  "tags": [
   "axis-bank",
   "credit-card",
   "fraud",
   "dispute",
   "chargeback",
   "block-card",
   "phishing",
   "unauthorized-transaction",
   "security"
  ],
  "title": "Phishing and Social Engineering",
  "text": "## CHUNK 8 — Phishing and Social Engineering\n\n### How do I identify and report phishing attempts related to Axis Bank?\n\n**Identifying phishing:**\n- Emails/SMSs with urgent messages like \"Your card will be blocked — verify now\"\n- Links that look like axisbank.com but are slightly different (e.g., axisbank-verify.com)\n- Calls claiming to be from Axis Bank asking for OTP, CVV, or card number\n- Offers that seem too good to be true (reward redemptions requiring card details)\n\n**Axis Bank will NEVER ask you for:**\n- Full card number\n- CVV\n- ATM PIN\n- Internet banking password\n- OTP\n\n**How to report phishing:**\n- Email: [email protected]\n- Call: 1860-419-5555\n- Cyber Crime Portal: cybercrime.gov.in (India national portal)\n\n---"
 },
 {
  "file_id": "kb_06_disputes_fraud_security",
  "topic": "Disputes, Fraud, and Card Security",
  "tags": [
   "axis-bank",
   "credit-card",
   "fraud",
   "dispute",
   "chargeback",
   "block-card",
   "phishing",
   "unauthorized-transaction",
   "security"
  ],
  "title": "Grievance Escalation for Fraud/Disputes",
  "text": "## CHUNK 9 — Grievance Escalation for Fraud/Disputes\n\n### What if Axis Bank doesn't resolve my fraud complaint satisfactorily?\n\n**Escalation path:**\n\n1. **Level 1 — Axis Bank Customer Care:** Call 1860-419-5555 or email [email protected]\n2. **Level 2 — Axis Bank Nodal Officer:** Email your complaint to Axis Bank's designated Nodal Officer (details available on axisbank.com under Grievance Redressal)\n3. **Level 3 — RBI Banking Ombudsman:**\n   - If your complaint is not resolved within **30 days** by Axis Bank\n   - File online at: cms.rbi.org.in\n   - The Ombudsman can award compensation up to ₹20 lakh\n4. **Consumer Forum:** Under the Consumer Protection Act, 2019 for unresolved disputes\n\n> Keep all written communication, complaint reference numbers, and transaction records when escalating."
 },
 {
  "file_id": "kb_07_rbi_regulations",
  "topic": "RBI Regulatory Guidelines for Credit Cards",
  "tags": [
   "RBI",
   "regulations",
   "master-direction-2022",
   "APR",
   "consumer-rights",
   "grievance",
   "interest-cap",
   "KFS",
   "credit-bureau"
  ],
  "title": "Overview of RBI Master Direction 2022",
  "text": "## CHUNK 1 — Overview of RBI Master Direction 2022\n\n### What is the RBI Master Direction on Credit Cards?\n\nThe **Reserve Bank of India (RBI) Master Direction — Credit Card and Debit Card – Issuance and Conduct Directions, 2022** was issued on **April 21, 2022** and became effective from **July 1, 2022**.\n\nThis direction consolidates all earlier circulars and guidelines on credit cards and debit cards into a single comprehensive regulation applicable to all scheduled commercial banks and NBFCs issuing credit cards in India.\n\n**Key objectives:**\n- Protect customers from unfair practices\n- Ensure transparency in interest and fee disclosure\n- Regulate the issuance, activation, and closure of cards\n- Establish grievance redressal standards\n\n---"
 },
 {
  "file_id": "kb_07_rbi_regulations",
  "topic": "RBI Regulatory Guidelines for Credit Cards",
  "tags": [
   "RBI",
   "regulations",
   "master-direction-2022",
   "APR",
   "consumer-rights",
   "grievance",
   "interest-cap",
   "KFS",
   "credit-bureau"
  ],
  "title": "Unsolicited Cards and Prior Consent",
  "text": "## CHUNK 2 — Unsolicited Cards and Prior Consent\n\n### Can a bank issue me a credit card without my consent?\n\n**No.** As per RBI Master Direction 2022:\n\n- Banks are **prohibited from issuing unsolicited (unrequested) credit cards**\n- **Prior and explicit consent** from the customer is mandatory before issuing a card\n- If an unsolicited card is received and the customer has NOT consented to activate it:\n  - The bank must **close the account within 7 working days** of the customer's request\n  - **No charges** can be levied on the customer for a card they did not request\n\n**Your right:** If you receive a credit card you did not apply for, you have the right to request closure at no cost within 30 days of receipt.\n\n---"
 },
 {
  "file_id": "kb_07_rbi_regulations",
  "topic": "RBI Regulatory Guidelines for Credit Cards",
  "tags": [
   "RBI",
   "regulations",
   "master-direction-2022",
   "APR",
   "consumer-rights",
   "grievance",
   "interest-cap",
   "KFS",
   "credit-bureau"
  ],
  "title": "Key Fact Statement (KFS)",
  "text": "## CHUNK 3 — Key Fact Statement (KFS)\n\n### What is a Key Fact Statement and am I entitled to receive one?\n\nYes. Under RBI rules, every credit card issuer **must provide a Key Fact Statement (KFS)** to every cardholder.\n\n**What the KFS must contain:**\n- Annual Percentage Rate (APR) for purchases, cash advances, balance transfers\n- All applicable fees and charges\n- Interest-free period details\n- Minimum payment warning and consequences of paying only the minimum\n- Grievance redressal contact information\n\n**When you receive it:** Along with your credit card welcome kit (physical or digital).\n\n**Your right:** You can request a copy of the KFS at any time from Axis Bank customer care or download it from the bank's website.\n\n---"
 },
 {
  "file_id": "kb_07_rbi_regulations",
  "topic": "RBI Regulatory Guidelines for Credit Cards",
  "tags": [
   "RBI",
   "regulations",
   "master-direction-2022",
   "APR",
   "consumer-rights",
   "grievance",
   "interest-cap",
   "KFS",
   "credit-bureau"
  ],
  "title": "Annualised Percentage Rate (APR)",
  "text": "## CHUNK 4 — Annualised Percentage Rate (APR)\n\n### What is APR and how is it different from the monthly interest rate?\n\n**APR (Annualised Percentage Rate)** is the total cost of credit expressed as a yearly rate, including all fees and charges, not just the stated monthly interest rate.\n\n**Why APR matters:**\n- Monthly rate of 3.6% looks small but = **43.2% APR annually**\n- APR includes processing fees, annual fees (amortised), and other charges, making it a true cost comparison tool\n\n**RBI requirement:** Banks must quote APR separately for:\n- Retail purchases\n- Cash advances\n- Balance transfers\n- Late payment scenarios\n\n**Where to find it:** On your Key Fact Statement, on the bank's website under each card's fee schedule, and on your monthly credit card statement.\n\n---"
 },
 {
  "file_id": "kb_07_rbi_regulations",
  "topic": "RBI Regulatory Guidelines for Credit Cards",
  "tags": [
   "RBI",
   "regulations",
   "master-direction-2022",
   "APR",
   "consumer-rights",
   "grievance",
   "interest-cap",
   "KFS",
   "credit-bureau"
  ],
  "title": "Billing Statement and Minimum Payment Warning",
  "text": "## CHUNK 5 — Billing Statement and Minimum Payment Warning\n\n### What are banks required to include in credit card billing statements under RBI rules?\n\nUnder RBI Master Direction 2022, credit card statements must include:\n\n1. **Minimum Amount Due (MAD)** prominently displayed\n2. **Consequences of paying only MAD** — a clear warning that paying only the minimum amount will result in higher interest charges and longer debt repayment period\n3. **Total outstanding balance and unbilled transactions**\n4. **Interest-free period remaining** (if applicable)\n5. **Payment due date** — at least **15 days (one fortnight)** from the statement date\n6. **Full APR and charges applicable**\n\n> Banks must send statements via email or mail. If a customer raises a query about any statement item, the bank must resolve and provide documentary evidence within **30 days**.\n\n---"
 },
 {
  "file_id": "kb_07_rbi_regulations",
  "topic": "RBI Regulatory Guidelines for Credit Cards",
  "tags": [
   "RBI",
   "regulations",
   "master-direction-2022",
   "APR",
   "consumer-rights",
   "grievance",
   "interest-cap",
   "KFS",
   "credit-bureau"
  ],
  "title": "Credit Limit and Over-Limit Rules",
  "text": "## CHUNK 6 — Credit Limit and Over-Limit Rules\n\n### Can the bank increase my credit limit without my consent?\n\n**No.** As per RBI regulations:\n\n- Banks **cannot enhance credit limits without the cardholder's explicit consent**\n- Customers have the right to **opt out of unsolicited credit limit increases**\n- The bank must have a formal process for customers to set their own credit limit (including requesting a reduction)\n\n**Your right:** If your credit limit was increased without your consent, you can request reversal and ask the bank to maintain the original limit.\n\n**Over-limit facility:**\n- Must also be based on prior consent\n- Over-limit charges can only be levied if the customer has opted in for the over-limit facility\n\n---"
 },
 {
  "file_id": "kb_07_rbi_regulations",
  "topic": "RBI Regulatory Guidelines for Credit Cards",
  "tags": [
   "RBI",
   "regulations",
   "master-direction-2022",
   "APR",
   "consumer-rights",
   "grievance",
   "interest-cap",
   "KFS",
   "credit-bureau"
  ],
  "title": "Card Closure Rights",
  "text": "## CHUNK 7 — Card Closure Rights\n\n### Can I close my Axis Bank credit card at any time? What are my rights?\n\n**Yes.** Under RBI rules:\n\n- Cardholders have the **unconditional right to close their credit card account at any time**\n- Banks **cannot insist on a minimum usage period** before closure\n- Closure must be processed within **7 working days** of the request\n- **No closure fee** can be charged unless the cardholder has unpaid dues\n\n**What happens at closure:**\n1. Clear all outstanding dues (balance must be zero)\n2. Redeem pending reward points (points are forfeited after closure)\n3. Cancel all auto-debits/ECS linked to the card\n4. Get written confirmation of closure from the bank\n\n> If the bank delays closure beyond 7 working days, they are in violation of RBI guidelines — escalate to the RBI Ombudsman.\n\n---"
 },
 {
  "file_id": "kb_07_rbi_regulations",
  "topic": "RBI Regulatory Guidelines for Credit Cards",
  "tags": [
   "RBI",
   "regulations",
   "master-direction-2022",
   "APR",
   "consumer-rights",
   "grievance",
   "interest-cap",
   "KFS",
   "credit-bureau"
  ],
  "title": "Grievance Redressal Under RBI Rules",
  "text": "## CHUNK 8 — Grievance Redressal Under RBI Rules\n\n### What is my right to complain under RBI regulations?\n\n**Bank's obligation:**\n- Every bank must have a **Board-approved grievance redressal policy** for credit cards\n- Banks must **publicize** their grievance mechanism on their website, monthly statements, and through other communications\n- Complaints must be acknowledged and resolved within a reasonable timeframe\n\n**Escalation timeline:**\n1. **Internal — Bank Customer Care:** Raise complaint via call/email/app\n2. **Internal — Nodal Officer:** If unresolved within 30 days\n3. **RBI Ombudsman:**\n   - File online at: **cms.rbi.org.in**\n   - If the bank has not responded within **30 days**, or if the response is unsatisfactory\n   - The Ombudsman can direct the bank to compensate the customer\n\n**RBI Ombudsman can award:**\n- Reversal of unauthorized charges\n- Compensation for mental agony and harassment\n- Awards up to **₹20 lakh** (₹1 crore in extreme cases involving fraud)\n\n---"
 },
 {
  "file_id": "kb_07_rbi_regulations",
  "topic": "RBI Regulatory Guidelines for Credit Cards",
  "tags": [
   "RBI",
   "regulations",
   "master-direction-2022",
   "APR",
   "consumer-rights",
   "grievance",
   "interest-cap",
   "KFS",
   "credit-bureau"
  ],
  "title": "Interest on Unauthorized Transactions and Delays",
  "text": "## CHUNK 9 — Interest on Unauthorized Transactions and Delays\n\n### What does RBI say about interest on disputed/unauthorized transactions?\n\nUnder RBI guidelines:\n\n- **If a transaction is disputed,** the bank should not continue charging interest on the disputed amount during the investigation period — they may apply a provisional credit\n- **If the bank wrongly levies charges:** The bank must reverse the charges with interest from the date of wrong debit\n- **Reporting timeline for zero liability:** Customer must report unauthorized transactions promptly:\n  - Within 3 working days: **Zero liability** (full reversal)\n  - 4–7 working days: **Limited liability** (capped at ₹5,000–₹25,000 depending on account type)\n  - Beyond 7 working days: Subject to bank policy\n\n> This policy applies only when the fraud was NOT due to the customer's own negligence (e.g., sharing OTP or PIN).\n\n---"
 },
 {
  "file_id": "kb_07_rbi_regulations",
  "topic": "RBI Regulatory Guidelines for Credit Cards",
  "tags": [
   "RBI",
   "regulations",
   "master-direction-2022",
   "APR",
   "consumer-rights",
   "grievance",
   "interest-cap",
   "KFS",
   "credit-bureau"
  ],
  "title": "Telemarketing and Harassment Rules",
  "text": "## CHUNK 10 — Telemarketing and Harassment Rules\n\n### What does RBI say about unsolicited calls from credit card companies?\n\nUnder RBI Master Direction 2022 and TRAI (Telecom Regulatory Authority of India) regulations:\n\n- **Telemarketing calls** can only be made between **10:00 AM and 7:00 PM** — no calls outside this window\n- Banks and their agents **cannot use coercive methods** to recover dues\n- Calling customers at odd hours or harassing them for payments is a violation of RBI's Fair Practice Code\n- Customers have the right to register on the **Do Not Disturb (DND) registry** to block promotional calls\n\n**How to register for DND:**\n- Call 1909 or SMS \"START 0\" to 1909 from your registered mobile number"
 },
 {
  "file_id": "kb_08_account_management",
  "topic": "Credit Card Account Management",
  "tags": [
   "axis-bank",
   "credit-card",
   "credit-limit",
   "upgrade",
   "PIN",
   "address-change",
   "closure",
   "international",
   "contactless",
   "virtual-card"
  ],
  "title": "PIN Management",
  "text": "## CHUNK 1 — PIN Management\n\n### How do I set or change my Axis Bank Credit Card PIN?\n\n**Setting a new PIN:**\n1. **Axis Mobile App:** Cards → Credit Card → Set PIN → Enter new 4-digit PIN → Confirm\n2. **ATM:** Insert card → Select \"PIN Change\" → Enter old PIN (or generate new if it's the first time) → Set new PIN\n3. **Customer Care:** Call 1860-419-5555 to request a new PIN via IVR\n\n**Important PIN rules:**\n- Your PIN should not be a predictable number (e.g., 1234, 0000, birth year)\n- Never share your PIN with anyone — Axis Bank will NEVER ask for your PIN\n- If you suspect your PIN is compromised, change it immediately\n\n**Forgot PIN:**\n- Use Axis Mobile App or Internet Banking to reset your PIN using OTP authentication\n\n---"
 },
 {
  "file_id": "kb_08_account_management",
  "topic": "Credit Card Account Management",
  "tags": [
   "axis-bank",
   "credit-card",
   "credit-limit",
   "upgrade",
   "PIN",
   "address-change",
   "closure",
   "international",
   "contactless",
   "virtual-card"
  ],
  "title": "Credit Limit Management",
  "text": "## CHUNK 2 — Credit Limit Management\n\n### How can I increase or decrease my Axis Bank Credit Card credit limit?\n\n**Credit Limit Increase:**\n1. **Axis Mobile App:** Cards → Credit Card → Credit Limit → Request Increase\n2. **Internet Banking:** Cards → Manage Card → Credit Limit Enhancement\n3. **Customer Care:** Call 1860-419-5555\n\n**Eligibility for increase:**\n- Good payment history (no missed payments in last 6–12 months)\n- Income increase since card issuance\n- Low credit utilization on existing limit\n- Improved CIBIL score\n\n**Credit Limit Decrease (at customer request):**\n- Right to reduce your own credit limit is protected under RBI guidelines\n- Useful for controlling spending or reducing risk exposure\n\n> **Important (RBI Rule):** Axis Bank cannot increase your credit limit without your **explicit consent**. If you receive an unsolicited increase, you can request reversal.\n\n---"
 },
 {
  "file_id": "kb_08_account_management",
  "topic": "Credit Card Account Management",
  "tags": [
   "axis-bank",
   "credit-card",
   "credit-limit",
   "upgrade",
   "PIN",
   "address-change",
   "closure",
   "international",
   "contactless",
   "virtual-card"
  ],
  "title": "Card Upgrade or Downgrade",
  "text": "## CHUNK 3 — Card Upgrade or Downgrade\n\n### Can I upgrade my Axis Bank Credit Card to a higher variant?\n\nYes, subject to eligibility.\n\n**Upgrade Process:**\n1. Contact Axis Bank customer care at 1860-419-5555\n2. Or visit any Axis Bank branch\n3. The bank will assess your eligibility based on income, credit history, and spending behaviour\n4. If approved, a new card is issued — your account number remains the same\n\n**Downgrade:**\n- You may also request to downgrade to a lower-fee card variant\n- Useful if you want to retain the account history but reduce fees\n\n**Important notes:**\n- Reward points balance typically carries over on upgrade\n- EMI conversions in progress may be affected — check with customer care\n- Annual fee changes take effect from the next billing cycle\n\n---"
 },
 {
  "file_id": "kb_08_account_management",
  "topic": "Credit Card Account Management",
  "tags": [
   "axis-bank",
   "credit-card",
   "credit-limit",
   "upgrade",
   "PIN",
   "address-change",
   "closure",
   "international",
   "contactless",
   "virtual-card"
  ],
  "title": "International Transaction Management",
  "text": "## CHUNK 4 — International Transaction Management\n\n### How do I enable or disable international transactions on my Axis Bank Credit Card?\n\nBy default, international transactions may be enabled on your card. You can control this via:\n\n**Axis Mobile App:**\nCards → Credit Card → Card Controls → International Transactions → Toggle On/Off\n\n**Controls available:**\n- Enable/disable international usage (online + physical)\n- Enable/disable contactless payments\n- Enable/disable online transactions\n- Set temporary/permanent transaction limits per channel\n\n**Recommendation:** Keep international transactions disabled when not travelling abroad to prevent fraudulent international charges.\n\n**Forex tip:** Inform Axis Bank before international travel to prevent your card being blocked for suspected unusual activity.\n\n---"
 },
 {
  "file_id": "kb_08_account_management",
  "topic": "Credit Card Account Management",
  "tags": [
   "axis-bank",
   "credit-card",
   "credit-limit",
   "upgrade",
   "PIN",
   "address-change",
   "closure",
   "international",
   "contactless",
   "virtual-card"
  ],
  "title": "Virtual Credit Card",
  "text": "## CHUNK 5 — Virtual Credit Card\n\n### Does Axis Bank offer a virtual credit card?\n\nYes. Axis Bank provides a **virtual credit card** for secure online transactions.\n\n- **What it is:** A temporary card number with a limited validity period generated for a specific online transaction\n- **Purpose:** Protects your actual card number from being exposed to merchants\n- **How to generate:** Axis Mobile App → Cards → Virtual Card → Generate\n\n> Virtual cards are particularly useful for first-time purchases on new or untrusted websites.\n\n---"
 },
 {
  "file_id": "kb_08_account_management",
  "topic": "Credit Card Account Management",
  "tags": [
   "axis-bank",
   "credit-card",
   "credit-limit",
   "upgrade",
   "PIN",
   "address-change",
   "closure",
   "international",
   "contactless",
   "virtual-card"
  ],
  "title": "Changing Personal Details",
  "text": "## CHUNK 6 — Changing Personal Details\n\n### How do I update my address, mobile number, or email on my Axis Bank Credit Card?\n\n**Mobile Number Update:**\n- Must be done at an Axis Bank branch with ID proof (cannot be changed digitally for security reasons)\n\n**Email Address Update:**\n1. Axis Mobile App → Profile → Contact Details → Update Email\n2. Internet Banking → Settings → Update Email\n3. Customer care: 1860-419-5555\n\n**Address Update:**\n1. Axis Mobile App → Profile → Address → Update\n2. Internet Banking\n3. Branch visit with address proof (Aadhaar/utility bill)\n\n**Important:** Keep your contact details updated to ensure you receive transaction alerts, OTPs, and statements without interruption.\n\n---"
 },
 {
  "file_id": "kb_08_account_management",
  "topic": "Credit Card Account Management",
  "tags": [
   "axis-bank",
   "credit-card",
   "credit-limit",
   "upgrade",
   "PIN",
   "address-change",
   "closure",
   "international",
   "contactless",
   "virtual-card"
  ],
  "title": "EMI Conversion for Existing Purchases",
  "text": "## CHUNK 7 — EMI Conversion for Existing Purchases\n\n### How do I convert an existing large purchase on my card to EMI?\n\nIf you have already made a large purchase and want to spread the cost:\n\n**Post-purchase EMI conversion:**\n1. **Axis Mobile App:** Cards → Transactions → Select Transaction → Convert to EMI → Choose Tenure\n2. **Customer Care:** Call 1860-419-5555 within 30 days of the transaction\n\n**Eligibility:**\n- Transaction must be ≥ ₹2,500\n- Not applicable for: fuel, gold/jewellery, cash advances, rent, wallet reloads\n- Card should not be delinquent\n\n**Processing fee:** May apply — check the specific offer terms at the time of conversion.\n\n---"
 },
 {
  "file_id": "kb_08_account_management",
  "topic": "Credit Card Account Management",
  "tags": [
   "axis-bank",
   "credit-card",
   "credit-limit",
   "upgrade",
   "PIN",
   "address-change",
   "closure",
   "international",
   "contactless",
   "virtual-card"
  ],
  "title": "Card Closure Process",
  "text": "## CHUNK 8 — Card Closure Process\n\n### How do I close/cancel my Axis Bank Credit Card?\n\n**Pre-closure checklist:**\n1. Clear all outstanding dues (full balance must be zero)\n2. Redeem all pending EDGE Reward Points (they are forfeited on closure)\n3. Cancel standing instructions/auto-debits linked to the card\n4. Destroy the physical card after closure confirmation\n\n**How to close:**\n1. **Customer Care:** Call 1860-419-5555 and request closure → Receive reference number\n2. **Written Request:** Send a letter to Axis Bank's Credit Card Division with your request\n3. **Branch:** Visit any branch to submit a closure request in writing\n\n**Timeline:** As per RBI guidelines, closure must be processed within **7 working days** of your request.\n\n**Confirmation:** Request a written/email confirmation of closure for your records.\n\n**No Objection Certificate (NOC):** After closure, request an NOC from Axis Bank confirming the account is fully settled.\n\n---"
 },
 {
  "file_id": "kb_08_account_management",
  "topic": "Credit Card Account Management",
  "tags": [
   "axis-bank",
   "credit-card",
   "credit-limit",
   "upgrade",
   "PIN",
   "address-change",
   "closure",
   "international",
   "contactless",
   "virtual-card"
  ],
  "title": "Contactless Payments (Tap & Pay)",
  "text": "## CHUNK 9 — Contactless Payments (Tap & Pay)\n\n### How does contactless payment work on my Axis Bank Credit Card?\n\nAxis Bank credit cards support **contactless payments** using NFC (Near Field Communication) technology.\n\n- **How to use:** Tap your card on a contactless-enabled POS terminal (look for the contactless symbol)\n- **Transaction limit:** ₹5,000 per contactless tap (PIN required for higher amounts, as per RBI guidelines)\n- **Security:** Each contactless transaction generates a unique token — your actual card number is never transmitted\n- **Enable/Disable:** Via Axis Mobile App → Cards → Card Controls → Contactless Payments\n\n> If you prefer not to use contactless, you can disable it in the app and use chip+PIN for all transactions.\n\n---"
 },
 {
  "file_id": "kb_08_account_management",
  "topic": "Credit Card Account Management",
  "tags": [
   "axis-bank",
   "credit-card",
   "credit-limit",
   "upgrade",
   "PIN",
   "address-change",
   "closure",
   "international",
   "contactless",
   "virtual-card"
  ],
  "title": "Customer Care and Contact Information",
  "text": "## CHUNK 10 — Customer Care and Contact Information\n\n### How can I contact Axis Bank Credit Card customer service?\n\n| Channel | Contact | Availability |\n|---|---|---|\n| Customer Care (India) | 1860-419-5555 | 24x7 |\n| Customer Care (Alternate) | 1860-500-5555 | 24x7 |\n| NRI customers | +91-22-6798-7700 | 24x7 |\n| Email (general) | [email protected] | Business hours |\n| Email (disputes) | [email protected] | Business hours |\n| Fraud Reporting Email | [email protected] | 24x7 |\n| SMS Banking | 5676782 | 24x7 |\n| Axis Mobile App | Available on iOS and Android | 24x7 |\n| Website | www.axisbank.com | 24x7 |\n| Grievance Portal | application.axisbank.co.in | 24x7 |"
 }
];
